language: node_js
node_js:
  - 14

services:
  - docker

build_images:
  - docker compose -f docker-compose-build.yaml build --parallel

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
push_images:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - export IMG_FRONTEND=udagram-frontend
  - export IMG_API_USER=udagram-api-user
  - export IMG_API_FEED=udagram-api-feed
  - export IMG_REVERSEPROXY=reverseproxy
  # Tag images
  - docker tag $IMG_FRONTEND $DOCKER_USER/$IMG_FRONTEND
  - docker tag $IMG_API_USER $DOCKER_USER/$IMG_API_USER
  - docker tag $IMG_API_FEED $DOCKER_USER/$IMG_API_FEED
  - docker tag $IMG_REVERSEPROXY $DOCKER_USER/$IMG_REVERSEPROXY
  # Push images to repo
  - docker push $DOCKER_USER/$IMG_FRONTEND
  - docker push $DOCKER_USER/$IMG_API_USER
  - docker push $DOCKER_USER/$IMG_API_FEED
  - docker push $DOCKER_USER/$IMG_REVERSEPROXY
