apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-user-deploy
  name: backend-user
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-user-deploy
  type: ClusterIP